### ISSUE TITLE
Alfred wants to update the workflow over and over and over again...

### ISSUE THREAD

**Issue by luuuis** [vegardinho/alfred_bluetooth_controller#43]
Often when I use the Cmd+Alt+B hotkey I am prompted by Alfred to update the workflow. This can happen once a day or multiple times a day.

<img width="1187" alt="Image" src="https://github.com/user-attachments/assets/ac1a4fd4-63d2-4dc1-969b-85c19c13b360" />

Even if choose to update I will get the same prompt later and the workflow version that gets downloaded is always the same: `Bluetooth.Controller.v4.2.alfredworkflow`.

Is there anything I can do to prevent this?

**Comment by vegardinho** [comment]
I think this is because I forgot to update the version tag in the workflow settings. It therefore always found a "newer" release on github. Fixed with release v4.2.1 out now.

**Comment by luuuis** [comment]
@vegardinho I'm unfortunately still experiencing this with 4.2.1. Any ideas on other possible causes?

**Comment by vegardinho** [comment]
Thanks for letting me know! I now found the reason, my .git files were in the wrong folder (probably duplicated the workflow to test something and then chose to keep the wrong workflow), so the newest info.plist file used for comparing versions wasn't uploaded to github - that means OneUpdater was comparing against an old version number.

It should be fixed now with abca78e5c5c9feed95bb6e91fc707838b824e577. (No need to publish new version, as only the check against version number is wrong.)

Do let me know if you still have issues!
